on: [push]

name: Aikido Scan
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:v1.0.21
    steps: 
      - uses: actions/checkout@v4 
      - name: Run scan
        run: aikido-local-scanner scan . --apikey ${{ secrets.AIKIDO_API_KEY }} --repositoryname laravel-trap --branchname ${{ github.ref }}
